server:
  port: 8080
  servlet:
    context-path: /Library

mybatis:
  type-aliases-package: com.example.demo.mapper
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/library?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

